//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _FEZ_POWER_H_
#define _FEZ_POWER_H_

#include <TinyCLR_Interop.h>
struct Library_FEZ_Power_FEZ_Power_ThreadManagment
{
    static const int FIELD_STATIC__debugPort = 0;
    static const int FIELD_STATIC__powerPort = 1;
    static const int FIELD_STATIC__wirelessPort = 2;
    static const int FIELD_STATIC__relayPort = 3;

    static const int FIELD__actionEvent = 1;
    static const int FIELD__actionQueue = 2;
    static const int FIELD__responseQueue = 3;
    static const int FIELD__tx = 4;
    static const int FIELD__wirelessThread = 5;
    static const int FIELD__powerThread = 6;
    static const int FIELD__actionThread = 7;
    static const int FIELD__mSeq = 8;
    static const int FIELD__myID = 9;
    static const int FIELD__AppVersion = 10;
    static const int FIELD__APIVersion = 11;
    static const int FIELD__ChipVersion = 12;
    static const int FIELD__lastPower = 13;


    //--//

};

struct Library_FEZ_Power_FEZ_Power_ThreadManagment__ActionStruct
{
    static const int FIELD__action = 1;
    static const int FIELD__destination = 2;
    static const int FIELD__parameter = 3;


    //--//

};

struct Library_FEZ_Power_FEZ_Power_CRC
{
    static const int FIELD_STATIC__crc8Table = 4;


    //--//

};

struct Library_FEZ_Power_FEZ_Power_Resources
{
    static const int FIELD_STATIC__manager = 5;


    //--//

};

struct Library_FEZ_Power_FEZ_Power_StringExtensions
{
    static const int FIELD_STATIC__hexes = 6;


    //--//

};

struct Library_FEZ_Power_FEZ_Power_Transmit
{
    static const int FIELD_STATIC__serialPort = 7;
    static const int FIELD_STATIC__responseQueue = 8;
    static const int FIELD_STATIC__sendEvent = 9;
    static const int FIELD_STATIC__sendQueue = 10;
    static const int FIELD_STATIC__sendOK = 11;
    static const int FIELD_STATIC__broadcast = 12;
    static const int FIELD_STATIC__headerRPS = 13;
    static const int FIELD_STATIC__header4BS = 14;
    static const int FIELD_STATIC__headerSYS_EX = 15;
    static const int FIELD_STATIC__headerCommand = 16;


    //--//

};

struct Library_FEZ_Power_FEZ_Power_ThreadManagment__ResponseStruct
{
    static const int FIELD__r = 1;
    static const int FIELD__destination = 2;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_FEZ_Power;

#endif  //_FEZ_POWER_H_
